#include "ofps_core.h"
#include "ofps_settings_schema.h"
#include "test_abi_pod_list.h"
#include "test_settings_golden.h"
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <set>
#include <string>
#include <type_traits>
extern "C" uint32_t OfpsAbiSizesInC(uint32_t *out, uint32_t capacity); extern "C" uint32_t OfpsAbiConstantsInC(void); static_assert(OFPS_ABI_VERSION == 1u, "public contract requires ABI 1"); static_assert(OFPS_SET_COUNT <= OFPS_SETTINGS_MAX, "OfpsSettingsValues::v must hold every setting id"); static_assert(OFPS_SET_COUNT == 45, "45 ids in plan 1: 22 persisted keys + 23 diagnostics; ids are append-only"); static_assert(OFPS_GROUP_COUNT == 9, "nine groups, Mode .. Diagnostics");
#define OFPS_POD(T) \
static_assert(std::is_standard_layout_v<T> && std::is_trivially_copyable_v<T>, #T " must be a POD"); \
static_assert(offsetof(T, size) == 0, #T "::size must be the first field")
OFPS_POD(OfpsVersion); OFPS_POD(OfpsResource); OFPS_POD(OfpsFrameInputs); OFPS_POD(OfpsModelInputs); OFPS_POD(OfpsFeatureDesc); OFPS_POD(OfpsEvalResult); OFPS_POD(OfpsFencePoint); OFPS_POD(OfpsEventData); OFPS_POD(OfpsHostCaps); OFPS_POD(OfpsStatus); OFPS_POD(OfpsLayoutPreview); OFPS_POD(OfpsSettingsValues);
#undef OFPS_POD
static_assert(std::is_standard_layout_v<OfpsStatusRow> && std::is_standard_layout_v<OfpsSettingDesc> && std::is_standard_layout_v<OfpsVisibleIf> && std::is_standard_layout_v<OfpsRect> && std::is_standard_layout_v<OfpsRectF> && std::is_standard_layout_v<OfpsSettingValue>); constexpr bool k64 = sizeof(void *) == 8; static_assert(sizeof(OfpsVersion) == 24 && sizeof(OfpsRect) == 16 && sizeof(OfpsRectF) == 16); static_assert(sizeof(OfpsResource) == (k64 ? 48u : 36u));
static_assert(offsetof(OfpsResource, res) == (k64 ? 8u : 4u)); static_assert(offsetof(OfpsResource, rect) == (k64 ? 20u : 12u)); static_assert(offsetof(OfpsResource, subresource) == (k64 ? 40u : 32u)); static_assert(sizeof(OfpsFrameInputs) == (k64 ? 560u : 420u)); static_assert(offsetof(OfpsFrameInputs, codecInputs) == (k64 ? 344u : 256u)); static_assert(offsetof(OfpsFrameInputs, colorDomain) == (k64 ? 552u : 416u));
static_assert(sizeof(OfpsModelInputs) == (k64 ? 376u : 284u)); static_assert(offsetof(OfpsModelInputs, width) == (k64 ? 364u : 276u)); static_assert(sizeof(OfpsFeatureDesc) == (k64 ? 32u : 24u)); static_assert(offsetof(OfpsFeatureDesc, adapterLuid) == (k64 ? 24u : 16u)); static_assert(sizeof(OfpsEvalResult) == 16); static_assert(sizeof(OfpsFencePoint) == (k64 ? 24u : 16u) && offsetof(OfpsFencePoint, value) == (k64 ? 16u : 8u)); static_assert(sizeof(OfpsEventData) == (k64 ? 32u : 16u));
static_assert(sizeof(OfpsHostCaps) == 8); static_assert(sizeof(OfpsStatus) == (k64 ? 136u : 120u)); static_assert(offsetof(OfpsStatus, evaluations) == 48 && offsetof(OfpsStatus, reason) == 104); static_assert(sizeof(OfpsStatusRow) == (k64 ? 32u : 16u)); static_assert(sizeof(OfpsLayoutPreview) == 132 && offsetof(OfpsLayoutPreview, diagnosticFlags) == 128); static_assert(sizeof(OfpsSettingValue) == 4);
static_assert(sizeof(OfpsSettingsValues) == 536 && offsetof(OfpsSettingsValues, v) == 8 && offsetof(OfpsSettingsValues, explicitMask) == 520); static_assert(sizeof(OfpsVisibleIf) == 12); static_assert(sizeof(OfpsSettingDesc) == (k64 ? 96u : 68u)); static_assert(offsetof(OfpsSettingDesc, defaultValue) == (k64 ? 52u : 32u)); namespace { int failures = 0; void Check(bool condition, const std::string &message) { if (!condition) { std::cerr << "FAIL: " << message << '\n'; ++failures; } }
bool Near(float lhs, float rhs) { return std::fabs(lhs - rhs) <= 1.0e-6f; } bool Integral(float value) { return std::floor(value) == value; } std::string RowName(uint32_t id) { const OfpsSettingDesc &d = kOfpsSettings[id]; return "id " + std::to_string(id) + " (" + (d.iniKey != nullptr ? d.iniKey : "<null>") + ")"; } float DefaultAsFloat(const OfpsSettingDesc &d) {
return d.type == OFPS_TYPE_FLOAT ? d.defaultValue.f : static_cast<float>(d.defaultValue.i); } void TestRowsAndKeys() { std::set<std::string> keys; for (uint32_t i = 0; i < OFPS_SET_COUNT; ++i) { const OfpsSettingDesc &d = kOfpsSettings[i]; Check(d.id == i, "row " + std::to_string(i) + " carries its own id"); Check(d.iniKey != nullptr && d.iniKey[0] != '\0', "row " + std::to_string(i) + " has an ini key"); Check(d.label != nullptr && d.label[0] != '\0', RowName(i) + " has a label");
Check(d.help != nullptr && d.help[0] != '\0', RowName(i) + " has a help text"); if (d.iniKey != nullptr) Check(keys.insert(d.iniKey).second, RowName(i) + ": ini key is unique"); Check(std::strchr(d.iniKey != nullptr ? d.iniKey : "", ' ') == nullptr && std::strchr(d.iniKey != nullptr ? d.iniKey : "", '=') == nullptr, RowName(i) + ": ini key has no space or '='"); } }
void TestGroups() { uint32_t previous = 0; uint32_t collapsedByGroup[OFPS_GROUP_COUNT] = {}; uint32_t rowsByGroup[OFPS_GROUP_COUNT] = {}; for (uint32_t i = 0; i < OFPS_SET_COUNT; ++i) { const OfpsSettingDesc &d = kOfpsSettings[i]; Check(d.group < OFPS_GROUP_COUNT, RowName(i) + ": group is known"); if (d.group >= OFPS_GROUP_COUNT) continue; Check(d.group >= previous, RowName(i) + ": groups appear in enum order (Mode .. Diagnostics) and contiguously"); previous = d.group; ++rowsByGroup[d.group];
if (d.flags & OFPS_FLAG_COLLAPSED_GROUP) ++collapsedByGroup[d.group]; } for (uint32_t g = 0; g < OFPS_GROUP_COUNT; ++g) Check(collapsedByGroup[g] == 0 || collapsedByGroup[g] == rowsByGroup[g], "group " + std::to_string(g) + ": OFPS_FLAG_COLLAPSED_GROUP is set on all of its rows or on none"); Check(rowsByGroup[OFPS_GROUP_MODE] == 2 && rowsByGroup[OFPS_GROUP_ZONE_SIZE] == 6 && rowsByGroup[OFPS_GROUP_ZONE_POSITION] == 5 &&
rowsByGroup[OFPS_GROUP_OUTLINES] == 2 && rowsByGroup[OFPS_GROUP_OUTPUT_COLOUR] == 2 && rowsByGroup[OFPS_GROUP_TEMPORAL] == 3 && rowsByGroup[OFPS_GROUP_MODEL_PASSES] == 2 && rowsByGroup[OFPS_GROUP_MOTION_SOURCE] == 0 && rowsByGroup[OFPS_GROUP_DIAGNOSTICS] == 23, "rows per group: 2, 6, 5, 2, 2, 3, 2, 0 (Motion source arrives with NVOFA), 23"); Check(collapsedByGroup[OFPS_GROUP_DIAGNOSTICS] == 23, "Diagnostics is the collapsed group"); }
void TestTypesRangesAndFlags() { constexpr uint32_t kKnownFlags = OFPS_FLAG_PERSISTED | OFPS_FLAG_DIAGNOSTIC | OFPS_FLAG_REBUILDS_MODEL | OFPS_FLAG_ADVANCED | OFPS_FLAG_COLLAPSED_GROUP; constexpr uint32_t kKnownCaps = OFPS_CAP_PRE_UPSCALE | OFPS_CAP_MODEL_RESOLUTION | OFPS_CAP_DEFERRED_MODEL_CREATION | OFPS_CAP_BACKGROUND_MODEL | OFPS_CAP_OPTICAL_FLOW | OFPS_CAP_QUEUES;
for (uint32_t i = 0; i < OFPS_SET_COUNT; ++i) { const OfpsSettingDesc &d = kOfpsSettings[i]; const std::string name = RowName(i); Check(d.type <= OFPS_TYPE_ENUM, name + ": type is known"); Check(d.minValue <= d.maxValue, name + ": min <= max"); const float def = DefaultAsFloat(d); Check(def >= d.minValue && def <= d.maxValue, name + ": default lies in [min, max]");
if (d.type != OFPS_TYPE_FLOAT) Check(Integral(d.minValue) && Integral(d.maxValue), name + ": integer types have integral bounds"); if (d.type == OFPS_TYPE_BOOL) Check(d.minValue == 0.0f && d.maxValue == 1.0f && (d.defaultValue.i == 0 || d.defaultValue.i == 1), name + ": bool is 0..1"); if (d.type == OFPS_TYPE_ENUM) { Check(d.enumLabels != nullptr, name + ": enum has labels"); if (d.enumLabels != nullptr) { uint32_t labels = 0; while (d.enumLabels[labels] != nullptr) ++labels;
Check(labels == static_cast<uint32_t>(d.maxValue - d.minValue) + 1u, name + ": one label per enum value, null-terminated"); } } else { Check(d.enumLabels == nullptr, name + ": only enums carry labels"); } Check((d.flags & ~kKnownFlags) == 0, name + ": only known flags"); const bool persisted = (d.flags & OFPS_FLAG_PERSISTED) != 0; const bool diagnostic = (d.flags & OFPS_FLAG_DIAGNOSTIC) != 0; Check(persisted != diagnostic, name + ": exactly one of Persisted / Diagnostic");
const char *key = d.iniKey != nullptr ? d.iniKey : ""; if (diagnostic) { Check(std::strncmp(key, "Debug", 5) == 0, name + ": diagnostics are today's Debug* keys"); Check(d.group == OFPS_GROUP_DIAGNOSTICS, name + ": diagnostics live in the Diagnostics group"); } else { Check(std::strncmp(key, "Debug", 5) != 0 && d.group != OFPS_GROUP_DIAGNOSTICS, name + ": persisted keys are never Debug*"); }
Check(d.visibleIf.op <= OFPS_VIS_GT && d.visibleIf.settingId < OFPS_SET_COUNT, name + ": visibleIf is well-formed"); if (d.visibleIf.op != OFPS_VIS_ALWAYS) Check(d.visibleIf.settingId != i, name + ": a visibility condition refers to another setting"); Check(d.rangeFrom <= 1u, name + ": rangeFrom is 0 or 1"); Check((d.hostCap & ~kKnownCaps) == 0, name + ": hostCap is a known capability"); Check(d.customWidget == 0u, name + ": plan 1 has no custom widgets in the table"); } }
void TestTodaysValues() { for (const Golden &g : kToday) { const OfpsSettingDesc &d = kOfpsSettings[g.id]; const std::string name = std::string("today's ") + g.iniKey; Check(d.iniKey != nullptr && std::strcmp(d.iniKey, g.iniKey) == 0, name + ": ini key"); Check(d.type == static_cast<uint32_t>(g.type), name + ": type"); Check(Near(d.minValue, g.lo) && Near(d.maxValue, g.hi), name + ": range"); Check(Near(DefaultAsFloat(d), g.def), name + ": default");
Check(d.rangeFrom == g.rangeFrom, name + ": rangeFrom (Offset and Work shift come from GetSettingRange)"); } for (OfpsSettingId id : {OFPS_SET_MODE, OFPS_SET_WORK_X, OFPS_SET_WORK_Y, OFPS_SET_GLOBAL_SCALE, OFPS_SET_MODEL_PASSES}) Check((kOfpsSettings[id].flags & OFPS_FLAG_REBUILDS_MODEL) != 0, RowName(id) + " rebuilds the model");
Check((kOfpsSettings[OFPS_SET_FLAGS].flags & OFPS_FLAG_ADVANCED) != 0, "Flags is advanced"); Check(kOfpsSettings[OFPS_SET_TEMPORAL_MAX_QUEUE].visibleIf.settingId == OFPS_SET_TEMPORAL_MODE && kOfpsSettings[OFPS_SET_TEMPORAL_MAX_QUEUE].visibleIf.op == OFPS_VIS_EQ && kOfpsSettings[OFPS_SET_TEMPORAL_MAX_QUEUE].visibleIf.value == 3, "TemporalMaxQueue shows in background mode only (overlay_temporal.cpp)");
Check(kOfpsSettings[OFPS_SET_CENTER_X].visibleIf.settingId == OFPS_SET_MODE && kOfpsSettings[OFPS_SET_CENTER_X].visibleIf.value == 2, "Center X shows in Peripheral mode only (overlay.cpp)"); const char *const *modeLabels = kOfpsSettings[OFPS_SET_MODE].enumLabels; const char *const *warpLabels = kOfpsSettings[OFPS_SET_DEBUG_WARP_PATH].enumLabels;
Check(modeLabels != nullptr && warpLabels != nullptr && std::strcmp(modeLabels[2], "Peripheral") == 0 && std::strcmp(warpLabels[1], "compute") == 0, "enum labels follow the value order"); } void TestCLayout() {
#define OFPS_ABI_ENTRY(expression) static_cast<uint32_t>(expression),
const uint32_t fromCpp[] = { OFPS_ABI_POD_LIST(OFPS_ABI_ENTRY) };
#undef OFPS_ABI_ENTRY
constexpr uint32_t kCount = static_cast<uint32_t>(sizeof(fromCpp) / sizeof(fromCpp[0])); uint32_t fromC[kCount] = {}; Check(OfpsAbiSizesInC(fromC, kCount) == kCount, "the C side reports the same number of layout facts"); for (uint32_t i = 0; i < kCount; ++i) Check(fromC[i] == fromCpp[i], "layout fact " + std::to_string(i) + ": C " + std::to_string(fromC[i]) + " vs C++ " + std::to_string(fromCpp[i]));
Check(OfpsAbiConstantsInC() == OFPS_ABI_VERSION + OFPS_SET_COUNT * 1000u + OFPS_GROUP_COUNT * 1000000u, "the C side sees the same ABI version and enum counts"); } } int main() { TestRowsAndKeys(); TestGroups(); TestTypesRangesAndFlags(); TestTodaysValues(); TestCLayout(); if (failures == 0) std::cout << "settings values tests passed (" << OFPS_SET_COUNT << " ids)\n"; return failures == 0 ? EXIT_SUCCESS : EXIT_FAILURE; }
